import type { Metadata } from 'next'
import './globals.css'
import { AppProviders } from '@/components/app-providers'
import { AppLayout } from '@/components/app-layout'
import React from 'react'
// 1. Import the font loader
import { Space_Grotesk } from 'next/font/google'

export const metadata: Metadata = {
  title: 'Ccfullstack',
  description: 'Generated by create-solana-dapp',
}

// 2. Configure the font
const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  display: 'swap', // Best practice for font loading
  variable: '--font-space-grotesk', // Optional: for CSS variable usage
})

const links: { label: string; path: string }[] = [
  // More links...
  { label: 'Home', path: '/' },
  { label: 'Account', path: '/account' },
  { label: 'Ccfullstack Program', path: '/ccfullstack' },
]

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* 3. Apply the font className to the body */}
      <body className={`${spaceGrotesk.className} antialiased`}>
        <AppProviders>
          <AppLayout links={links}>{children}</AppLayout>
        </AppProviders>
      </body>
    </html>
  )
}

// Patch BigInt so we can log it using JSON.stringify without any errors
declare global {
  interface BigInt {
    toJSON(): string
  }
}

BigInt.prototype.toJSON = function () {
  return this.toString()
}